# This docker compose file for development only

version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=prananda
      - POSTGRES_PASSWORD=prananda
      - POSTGRES_DB=faucet-api
    ports:
      - '5431:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:6
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
